language: python
install: skip
services: 
  - docker
script:
  - "docker build -t jdiaz67/ezekiel17/devnote ."
after_success: 
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_ID\" --password-stdin"
  - "docker push jdiaz67/" 
deploy: 
  access_key_id: $AWS_ACCESS_KEY
  app: "DevNote"
  bucket_name: devnote-bucket
  bucket_path: docker
  env: Devnote-env
  provider: elasticbeanstalk
  region: us-west-2
  secret_access_key: $AWS_SECRET_KEY
  true: development